# 服务端口
server:
  port: 8304
  # 服务名
spring:
  application:
    name: service-user

  # 环境设置：dev、test、prod
  profiles:
    active: dev
  
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#公众号id和秘钥
# 硅谷课堂微信公众平台appId
wechat:
  mpAppId: xxx
## 硅谷课堂微信公众平台api秘钥
  mpAppSecret: xxx
# 授权回调获取用户信息接口地址
  userInfoUrl: http://ggkt.vipgz1.91tunnel.com/api/user/wechat/userInfo