# 服务端口
server:
  port: 8333

# 服务名
spring:
  application:
    name: service-gateway

  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true

  # service-vod模块配置
  # 设置路由id
      routes[0]:
        id: service-vod
        uri: lb://service-vod
        predicates: Path=/*/vod/**
      # service-vod模块配置
      # 设置路由id
      routes[1]:
        id: service-order
        uri: lb://service-order
        predicates: Path=/*/order/**

      # service-vod模块配置
      # 设置路由id
      routes[2]:
        id: service-user
        uri: lb://service-user
        predicates: Path=/*/user/**

      # service-vod模块配置
      # 设置路由id
      routes[3]:
        id: service-activity
        uri: lb://service-activity
        predicates: Path=/*/activity/**

      # service-vod模块配置
      # 设置路由id
      routes[4]:
        id: service-wechat
        uri: lb://service-wechat
        predicates: Path=/*/wechat/**

      # service-vod模块配置
      # 设置路由id
      routes[5]:
        id: service-live
        uri: lb://service-live
        predicates: Path=/*/live/**